# Generated by Django 5.1.1 on 2024-10-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_01_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
