# Generated by Django 5.1.1 on 2024-10-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_01_app', '0002_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
