# Generated by Django 5.1.1 on 2024-10-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_01_app', '0003_car_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
